### ISSUE TITLE
Search Module (Page gets stuck)

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1101]
In Search module, (for a company that has bulk data like Walkover) when user searches for a group that has a lot of data, like Sundry Debtors, then response is received from API end, however, on UI, page gets stuck.

ENV: PROD
Please fix this ASAP.

PFA screenshot.

**Comment by sagarnankani** [comment]
![uistuck.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46fd9d89379780a2cda5fd53b652fa912a5265296b51a27d20dce27fbd122e590c5d48ac41515a47fdfd8e28f4a42062c80d55b98e30063e937f03a6aa8317b500bf23894e80b3bd8d45c1ea3f37aa.png)

**Comment by sagarnankani** [comment]
![uistuck.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a65b8dc91fa530012048781/125516c66e82c728ace21e0d46fd9d89379780a2cda5fd53b652fa912a5265296b51a27d20dce27fbd122e590c5d48ac41515a47fdfd8e28f4a42062c80d55b98e30063e937f03a6aa8316b500bf23894e80b3be8f49c8ed3d37aa.png)

**Comment by apmeena** [comment]
@sagarnankani, I tried to handle this situation (Page gets stuck). But I was unable to solve the problem. 
This happens because we are getting a log of data from API approx `15,000` in a single API call and the same number of rows we are displaying in HTML page this is the reason.

We have two possible ways to handle this problem:
1. Use Index DB at client side
2. Use Paginated API

We need to take a decision then we can work on it.
