### ISSUE TITLE
Universal Date Picker - Last FY to Date not working properly

### ISSUE THREAD

**Issue by sagarnankani** [Walkover-Web-Solution/Giddh-New-Angular4-App#1277]
In Universal Date Picker - let's say today is 9th Sept 2018, and user selects "Last FY to Date" option, then date range is set to 1 Apr 18 to 9 Sept 18. This is correct.
However, net day if user selects the same option: "Last FY to Date" again, then still date range is set to  1 Apr 18 to 9 Sept 18. This is incorrect.

ENV: PROD
Please fix this ASAP.

PFA screenshot.

**Comment by apmeena** [comment]
@sagar, As of my discussion with @shubhendra sir, this issue will be fixed from API side and
mark it as a feature not a but.

Explanation: We are getting `from` and `to` from the API and we don't know which option user has selected, so for extending this functionality we will need to pass some more additional key to the API so that we will get proper value of `from` and `to`.
